server:
  port: 8888
  servlet:
    context-path: /config
spring:
  profiles:
    active: native
---
spring:
  profile: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///${user.dir}/files/eo
            - file:///${user.dir}/files/eo/auth
        encrypt:
          enabled: false

